### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by ViriatoII** [samiscoding/CiDas2019#1]
Dear @samiscoding ,

This looks very interesting, and the paper too. But have you actually released your program? There are no instructions, is it usable? 

Kind regards,
Ricardo

**Comment by samiscoding** [comment]
Thanks, @ViriatoII for showing an interest :) Unfortunately, we did not publish it as an easy-to-use resource, but it's definitely reusable if you already have a text file including the human-readable description of each protein cluster (you can use [https://github.com/groupschoof/AHRD] for this purpose), giving the path of the file in the `handler` function in `representativeFunctionDescriptionExtraction.py`.

**Comment by ViriatoII** [comment]
Thank you! I was thinking it was an alternative to AHRD instead of a complement.

Have a good evening,
RIcardo
